@echo off
setlocal

rem Define Vault Paths
set "VAULT_ROOT=%~dp0..\AI-Employee-Vault"
set "DONE_DIR=%VAULT_ROOT%\Done"

echo [CCR] Received Request.
echo [CCR] Prompt: %*

rem Attempt to run the real Claude Code
rem We use 'call' to avoid terminating the batch script
rem Adding -p to ensure it runs non-interactively
call ccr code -p %*

if %ERRORLEVEL% equ 0 (
    echo [CCR] Claude finished successfully.
    exit /b 0
)

rem Fallback: If Claude is not found or fails, we simulate the output for testing
echo [CCR] WARNING: 'claude' command not found or failed (Error Level: %ERRORLEVEL%).
echo [CCR] Entering SIMULATION MODE.
echo.

rem Simulate thinking time
timeout /t 2 /nobreak >nul

rem Create a timestamped project folder
rem Create a timestamped project folder
for /f %%I in ('powershell -Command "Get-Date -Format 'yyyyMMddHHmmss'"') do set TIMESTAMP=%%I
set "PROJECT_DIR=%DONE_DIR%\Simulated_Website_%TIMESTAMP%"

echo [CCR] Generating Mock Website in: %PROJECT_DIR%
mkdir "%PROJECT_DIR%"

rem Write Mock Index.html
(
echo ^<!DOCTYPE html^>
echo ^<html^>
echo ^<head^>
echo     ^<title^>Simulated Website^</title^>
echo     ^<style^>
echo         body { font-family: sans-serif; background: #f0f0f0; display: flex; justify-content: center; align-items: center; height: 100vh; }
echo         .card { background: white; padding: 2rem; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
echo         h1 { color: #333; }
echo     ^</style^>
echo ^</head^>
echo ^<body^>
echo     ^<div class="card"^>
echo         ^<h1^>Simulated Website Output^</h1^>
echo         ^<p^>This was generated by ccr.bat because 'claude' CLI was not reachable.^</p^>
echo         ^<p^>To enable real AI, ensure 'claude' is in your PATH.^</p^>
echo     ^</div^>
echo ^</body^>
echo ^</html^>
) > "%PROJECT_DIR%\index.html"

echo [CCR] Simulation Complete.
exit /b 1
