"""
Orchestrator - The Master Control Script for SAZA AI Employee.

Responsibilities:
1. Monitors /Inbox and /Needs_Action for new tasks
2. Creates Plan.md files for multi-step reasoning
3. Triggers Claude Code (via CCR) to execute tasks
4. Manages the approval workflow
5. Handles error recovery and logging
"""

import os
import time
import subprocess
import shutil
from pathlib import Path
from datetime import datetime
import logging
import json

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('Orchestrator')


class Orchestrator:
    """
    Central orchestrator that coordinates all SAZA components.
    Implements the Claude Reasoning Loop with Plan.md generation.
    """
    
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        
        # Core directories
        self.inbox_dir = self.vault_path / "Inbox"
        self.needs_action_dir = self.vault_path / "Needs_Action"
        self.pending_approval_dir = self.vault_path / "Pending_Approval"
        self.approved_dir = self.vault_path / "Approved"
        self.done_dir = self.vault_path / "Done"
        self.logs_dir = self.vault_path / "Logs"
        self.plans_dir = self.vault_path / "Plans"
        
        # Processed tracking
        self.processed_dir = self.inbox_dir / "Processed"
        
        # Scripts
        self.scripts_dir = self.vault_path.parent / "scripts"
        self.ccr_script = self.scripts_dir / "ccr.bat"
        
        # Ensure directories exist
        for dir_path in [self.needs_action_dir, self.pending_approval_dir, 
                         self.approved_dir, self.done_dir, self.logs_dir, 
                         self.plans_dir, self.processed_dir]:
            dir_path.mkdir(parents=True, exist_ok=True)
        
        # State
        self.check_interval = 30  # seconds
        self.max_retries = 3
    
    def log_event(self, message: str, level: str = "INFO"):
        """Log an event to the daily log file."""
        timestamp = datetime.now()
        log_file = self.logs_dir / f"orchestrator_{timestamp.strftime('%Y-%m')}.md"
        
        log_entry = f"- **{timestamp.strftime('%Y-%m-%d %H:%M:%S')}** [{level}]: {message}\n"
        
        with open(log_file, 'a', encoding='utf-8') as f:
            f.write(log_entry)
        
        if level == "ERROR":
            logger.error(message)
        else:
            logger.info(message)
    
    def create_plan(self, task_file: Path) -> Path:
        """
        Create a Plan.md file for a task.
        This implements the Claude Reasoning Loop.
        """
        task_content = task_file.read_text(encoding='utf-8')
        task_name = task_file.stem
        
        plan_content = f"""---
task_source: {task_file.name}
created: {datetime.now().isoformat()}
status: pending
---

# Plan: {task_name}

## Task Analysis

**Source File:** {task_file}

**Content:**
```
{task_content[:500]}{'...' if len(task_content) > 500 else ''}
```

## Execution Steps

- [ ] Step 1: Analyze the task requirements
- [ ] Step 2: Design the solution
- [ ] Step 3: Implement the solution
- [ ] Step 4: Verify the output
- [ ] Step 5: Move to Done and log completion

## Expected Output

The completed task output will be saved to `/Done/{task_name}/`

---
*Generated by SAZA Orchestrator*
"""
        
        plan_file = self.plans_dir / f"PLAN_{task_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        plan_file.write_text(plan_content, encoding='utf-8')
        
        self.log_event(f"Created plan: {plan_file.name}")
        return plan_file
    
    def trigger_ccr(self, task_file: Path, plan_file: Path) -> bool:
        """Trigger Claude Code Router to execute a task."""
        try:
            prompt = (
                f"You have a task to complete. "
                f"Read the plan at '{plan_file}' and the task at '{task_file}'. "
                f"Execute the plan step by step. "
                f"Save results to '{self.done_dir}'. "
                f"Follow CLAUDE.md and AGENTS.md standards."
            )
            
            self.log_event(f"Triggering CCR for task: {task_file.name}")
            
            # Execute CCR
            command = f'"{self.ccr_script}" -p "{prompt}"'
            result = subprocess.run(command, shell=True, capture_output=True, text=True)
            
            if result.returncode == 0:
                self.log_event(f"CCR completed successfully for: {task_file.name}")
                return True
            else:
                self.log_event(f"CCR failed for {task_file.name}: {result.stderr}", "ERROR")
                return False
                
        except Exception as e:
            self.log_event(f"Error triggering CCR: {e}", "ERROR")
            return False
    
    def process_inbox(self):
        """Process all files in the Inbox directory."""
        for task_file in self.inbox_dir.glob('*'):
            if task_file.is_file() and task_file.suffix.lower() in ['.txt', '.md']:
                logger.info(f"Processing inbox task: {task_file.name}")
                
                # Create a plan
                plan_file = self.create_plan(task_file)
                
                # Execute via CCR
                success = self.trigger_ccr(task_file, plan_file)
                
                if success:
                    # Archive the task file
                    archive_path = self.processed_dir / task_file.name
                    if archive_path.exists():
                        archive_path = self.processed_dir / f"{task_file.stem}_{int(time.time())}{task_file.suffix}"
                    shutil.move(str(task_file), str(archive_path))
                    self.log_event(f"Archived task: {task_file.name}")
    
    def process_needs_action(self):
        """Process files in the Needs_Action directory."""
        for task_file in self.needs_action_dir.glob('*'):
            if task_file.is_file() and task_file.suffix.lower() in ['.txt', '.md']:
                logger.info(f"Processing needs_action task: {task_file.name}")
                
                # Create a plan
                plan_file = self.create_plan(task_file)
                
                # Execute via CCR
                success = self.trigger_ccr(task_file, plan_file)
                
                if success:
                    # Archive the task file
                    archive_path = self.processed_dir / task_file.name
                    if archive_path.exists():
                        archive_path = self.processed_dir / f"{task_file.stem}_{int(time.time())}{task_file.suffix}"
                    shutil.move(str(task_file), str(archive_path))
                    self.log_event(f"Archived task: {task_file.name}")

    def process_approved(self):
        """Process approved actions that require execution."""
        for action_file in self.approved_dir.glob('*.md'):
            # Only process files directly in Approved, not subfolders
            if not action_file.is_file(): continue
            
            logger.info(f"Processing approved action: {action_file.name}")
            
            try:
                content = action_file.read_text(encoding='utf-8')
                
                # Check for types handled by other specialized scripts
                if 'type: whatsapp' in content or 'type: linkedin_post' in content:
                    logger.info(f"Skipping {action_file.name}, handled by specialized watcher.")
                    continue

                # Handle internal simulated actions
                if 'type: payment' in content:
                    self.log_event(f"Payment action approved (simulated): {action_file.name}")
                elif 'type: email' in content:
                    self.log_event(f"Email action approved (simulated): {action_file.name}")
                
                # Default: Move to Done for generic or completed actions
                done_path = self.done_dir / f"APPROVED_{action_file.name}"
                shutil.move(str(action_file), str(done_path))
                self.log_event(f"Completed approved action: {action_file.name}")
                
            except Exception as e:
                self.log_event(f"Error processing approved action {action_file.name}: {e}", "ERROR")
    
    def check_watcher_health(self) -> dict:
        """Check if watcher processes are running."""
        health = {
            'gmail_watcher': False,
            'inbox_watcher': False,
            'linkedin_watcher': False
        }
        
        try:
            result = subprocess.run(['tasklist'], capture_output=True, text=True)
            processes = result.stdout.lower()
            
            # Check for Python processes (simplified check)
            if 'python' in processes:
                health['gmail_watcher'] = True
                health['inbox_watcher'] = True
                health['linkedin_watcher'] = True
        except:
            pass
        
        return health
    
    def generate_daily_briefing(self):
        """Generate a daily CEO briefing (triggered by scheduler)."""
        today = datetime.now()
        briefing_file = self.vault_path / "Briefings" / f"briefing_{today.strftime('%Y-%m-%d')}.md"
        briefing_file.parent.mkdir(parents=True, exist_ok=True)
        
        # Count statistics
        done_today = sum(1 for f in self.done_dir.iterdir() 
                        if f.is_dir() and (today.timestamp() - f.stat().st_ctime) < 86400)
        pending_tasks = sum(1 for f in self.inbox_dir.glob('*.md')) + sum(1 for f in self.inbox_dir.glob('*.txt'))
        pending_approval = sum(1 for f in self.pending_approval_dir.rglob('*.md'))
        
        briefing_content = f"""---
generated: {today.isoformat()}
period: {today.strftime('%Y-%m-%d')}
---

# Daily CEO Briefing

## Summary
- **Tasks Completed Today:** {done_today}
- **Pending Tasks:** {pending_tasks}
- **Awaiting Approval:** {pending_approval}

## System Health
- Watchers: Online
- Orchestrator: Running

---
*Generated by SAZA AI Employee*
"""
        
        briefing_file.write_text(briefing_content, encoding='utf-8')
        self.log_event(f"Generated daily briefing: {briefing_file.name}")
        return briefing_file
    
    def run(self):
        """Main orchestrator loop."""
        logger.info("=" * 60)
        logger.info("SAZA Orchestrator Starting...")
        logger.info(f"Vault: {self.vault_path}")
        logger.info("=" * 60)
        
        self.log_event("Orchestrator started")
        
        while True:
            try:
                # Process inbox tasks
                self.process_inbox()
                
                # Process needs_action tasks
                self.process_needs_action()
                
                # Process approved actions
                self.process_approved()
                
                # Health check (every 10 iterations)
                # health = self.check_watcher_health()
                
            except Exception as e:
                self.log_event(f"Error in main loop: {e}", "ERROR")
            
            time.sleep(self.check_interval)


if __name__ == "__main__":
    VAULT = "d:/practice/AI_Employee/AI-Employee-Vault"
    
    orchestrator = Orchestrator(VAULT)
    orchestrator.run()
